name: Install & Build Checks

on:
  pull_request:
    branches: [staging, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
