name: Database Migration

on:
  push:
    branches: [staging, main]

env:
  DATABASE_URL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_DATABASE_URL || secrets.STAGING_DATABASE_URL }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Migrate DB
        run: npx prisma migrate deploy
